In [3]:
# we are checking the multicollinearity using Ordinary Least Square Method(OLS)
import statsmodels.api as sm
import pandas as pd
import os

In [9]:
os.listdir()

['.ipynb_checkpoints',
 'Advertising.csv',
 'Multicollinearity-master',
 'Multicollinearity-master.zip',
 'Salary_Data.csv',
 'Untitled.ipynb']

In [11]:
df = pd.read_csv('Advertising.csv')

In [14]:
X = df[['TV', 'radio','newspaper']]
y = df['sales']
df_adv.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [15]:
#Adding a constant value to Beta0 as it has no feature
X=sm.add_constant(X)

In [16]:
X

     const     TV  radio  newspaper
0      1.0  230.1   37.8       69.2
1      1.0   44.5   39.3       45.1
2      1.0   17.2   45.9       69.3
3      1.0  151.5   41.3       58.5
4      1.0  180.8   10.8       58.4
..     ...    ...    ...        ...
195    1.0   38.2    3.7       13.8
196    1.0   94.2    4.9        8.1
197    1.0  177.0    9.3        6.4
198    1.0  283.6   42.0       66.2
199    1.0  232.1    8.6        8.7

[200 rows x 4 columns]

In [23]:
# fitting the model usin g .fit function
# press shift tab to check exog(input) and endog(output) values
model=sm.OLS(y,X).fit()

In [24]:
model

In [25]:
# 1)check for  R-squared,Adj R-squared  is near to 1 so thats pretty good model
# 2) check for coeefieicnts are high or low,should be low for good model, id negative value, that feature can be deleted
# 3) check for std error
# 4) check for p value, should be less than0.05, if greater than , 0.05 u can deleet that value
#5)beta0=2.9389,
#beta1=0.048, which  means if there is unit inc in sales value,we need to inc expenditure of tv by 0.1885,
#beta2=0.1885, which  means if there is unit inc in sales value,we need to inc expenditure of radio by 0.1885,
#beta3=-0.0010, which mean  no neeed for expenditure because we have neagative value
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Sat, 02 Oct 2021   Prob (F-statistic):           1.58e-96
Time:                        21:32:28   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
radio          0.1885      0.009     21.893      0.000       0.172       0.206
newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
# check for coeffiecints less values
#R square and Adj R square ranges b/w 0  and 1, the more towards 1, means the model fitted in a good way,
# std errror are  less, which means that none of the features, hae multicollinearity  problem
# All the P values are less than 0.05, only 1 feature hae 0.860, says that we are making unnecesary expeniture on news paper,
#so we can reduce that, thats what it indicates
# here p value is less for newspaper so we can drop newspaper feature

In [26]:
#using plot  check correlation using .corr()
import matplotlib.pyplot as plt

In [27]:
# here correlation is  less
X.iloc[:,1:].corr()
#plotting corr,
# having less correlatuion . less than 0..05,no correlation between indeopenent features, so defiently i can say that no multicollineariy issue, so we can use this model

                 TV     radio  newspaper
TV         1.000000  0.054809   0.056648
radio      0.054809  1.000000   0.354104
newspaper  0.056648  0.354104   1.000000

In [30]:
# HIgh multicoolinearity
df_s=pd.read_csv('Salary_Data.csv')

In [34]:
df_s.head(2)

   YearsExperience   Age  Salary
0              1.1  21.0   39343
1              1.3  21.5   46205

In [62]:
X_s=df_s[['YearsExperience','Age']]

In [63]:
y_s=df_s['Salary']

In [64]:
# adding constant value
X_s=sm.add_constant(X_s)

In [65]:
X_s

    const  YearsExperience   Age
0     1.0              1.1  21.0
1     1.0              1.3  21.5
2     1.0              1.5  21.7
3     1.0              2.0  22.0
4     1.0              2.2  22.2
5     1.0              2.9  23.0
6     1.0              3.0  23.0
7     1.0              3.2  23.3
8     1.0              3.2  23.3
9     1.0              3.7  23.6
10    1.0              3.9  23.9
11    1.0              4.0  24.0
12    1.0              4.0  24.0
13    1.0              4.1  24.0
14    1.0              4.5  25.0
15    1.0              4.9  25.0
16    1.0              5.1  26.0
17    1.0              5.3  27.0
18    1.0              5.9  28.0
19    1.0              6.0  29.0
20    1.0              6.8  30.0
21    1.0              7.1  30.0
22    1.0              7.9  31.0
23    1.0              8.2  32.0
24    1.0              8.7  33.0
25    1.0              9.0  34.0
26    1.0              9.5  35.0
27    1.0              9.6  36.0
28    1.0             10.3  37.0
29    1.0             10.5  38.0

In [67]:
# fittinfg model
#endog=y,exog=x,
model2=sm.OLS(y_s,X_s).fit()

In [68]:
model2.summary()
# R square and adjusted R square ranges between 0-1, close to 1 means the model is fit in a good way
# Rsquare is also fine coz they are fitted v fine
#we have high coeff values, beta1=6153, i.e,if years of expereince changes by 1 unit, then output(salary) will be changed by 6153 times,
# we have Age:coeff=1836, if age will be inc by 1 unit than, salary will be changed by 1836 times, (for each year)
# these coeff are absoulutely fine
#check for standard errorit is becoming huge value,high valuebut we cant say just by seeing std error, we have to see P value also 
#beta1;years of exp[coeff] is high,so check for p value,so it is less, so its not a probem
# check for beta2;Age[coeff] is high,p value is 0.165,which is not less than 0.05so that means this gives an indication that there maty be some multicollinearity
#so in order to confirm that we check .corr,  check correlation plot

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.960
Model:                            OLS   Adj. R-squared:                  0.957
Method:                 Least Squares   F-statistic:                     323.9
Date:                Sat, 02 Oct 2021   Prob (F-statistic):           1.35e-19
Time:                        21:50:18   Log-Likelihood:                -300.35
No. Observations:                  30   AIC:                             606.7
Df Residuals:                      27   BIC:                             610.9
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const           -6661.9872   2.28e+04     -0.292      0.773   -5.35e+04    4.02e+04
YearsExperience  6153.3533   2337.092      2.633      0.014    1358.037    1.09e+04
Age              1836.0136   1285.034      1.429      0.165    -800.659    4472.686
==============================================================================
Omnibus:                        2.695   Durbin-Watson:                   1.711
Prob(Omnibus):                  0.260   Jarque-Bera (JB):                1.975
Skew:                           0.456   Prob(JB):                        0.372
Kurtosis:                       2.135   Cond. No.                         626.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [69]:
# we see here the correlation here is 98% correlation, 
# of we have such correlation then we can drop off one feature.
# which one to drop, ???
#go and check p value,the feature which  has high P value, can be dropped and train the model using only 1 feature
X_s.iloc[:,1:].corr()

                 YearsExperience       Age
YearsExperience         1.000000  0.987258
Age                     0.987258  1.000000